import { Property, Customer, Meeting, Lead, DashboardStats, AIRecommendation } from "@/types";

/**
 * Primärt objekt i Sollentuna via HusmanHagberg.
 * Data från husmanhagberg.se – bilder är placeholders.
 */

export const mockProperties: Property[] = [
  {
    id: "1",
    slug: "manhemsvagen-16b-edsviken",
    title: "Generös 5:a i Edsviken, Sollentuna",
    address: "Manhemsvägen 16B",
    city: "Sollentuna",
    area: "Edsviken",
    zipCode: "192 55",
    price: 11490000,
    pricePerSqm: 88385,
    status: "for_sale",
    type: "lagenhet",
    rooms: 5,
    livingArea: 130,
    description:
      "Rymlig 5 rok om 130 kvm i eftertraktade Edsviken, Sollentuna. Naturnära läge med närhet till vatten, service och goda kommunikationer. Objekt via HusmanHagberg Sollentuna.",
    shortDescription: "5 rok, 130 kvm i Edsviken. 11 490 000 kr.",
    features: ["Naturnära", "Edsviken", "Familjevänlig", "Förråd"],
    images: [
      {
        id: "1-1",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80",
        alt: "Manhemsvägen Edsviken",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.4285,
    longitude: 17.9585,
    bidStatus: "Budgivning",
    brokerId: "broker-1",
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-14T10:00:00Z",
    isFeatured: true,
  },
  {
    id: "2",
    slug: "militarvagen-10-viby",
    title: "Exklusiv villa i Viby, Sollentuna",
    address: "Militärvägen 10",
    city: "Sollentuna",
    area: "Viby",
    zipCode: "192 55",
    price: 16900000,
    pricePerSqm: 67465,
    status: "for_sale",
    type: "villa",
    rooms: 8,
    livingArea: 250.5,
    description:
      "Prestigevilla om 8 rok och ca 250 kvm i Viby, Sollentuna. Generösa ytor och attraktivt villaläge. Objekt via HusmanHagberg.",
    shortDescription: "Villa 8 rok, 250 kvm i Viby. Prestige.",
    features: ["Villa", "Prestige", "Stor tomt", "Garage"],
    images: [
      {
        id: "2-1",
        url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=80",
        alt: "Militärvägen Viby",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.4455,
    longitude: 17.9485,
    bidStatus: "Till salu",
    brokerId: "broker-1",
    createdAt: "2026-09-02T09:00:00Z",
    updatedAt: "2026-09-14T09:00:00Z",
    isFeatured: true,
  },
  {
    id: "3",
    slug: "aspvagen-27d-fagelsangen",
    title: "5 rok i Fågelsången, Sollentuna",
    address: "Aspvägen 27D",
    city: "Sollentuna",
    area: "Fågelsången",
    zipCode: "192 48",
    price: 4950000,
    pricePerSqm: 48058,
    status: "for_sale",
    type: "lagenhet",
    rooms: 5,
    livingArea: 103,
    description:
      "Välplanerad 5 rok om 103 kvm i Fågelsången, Sollentuna. Bra familjeplanlösning och trevligt område. Objekt via HusmanHagberg Sollentuna.",
    shortDescription: "5 rok, 103 kvm i Fågelsången. 4 950 000 kr.",
    features: ["Familjevänlig", "Förråd", "Bra läge"],
    images: [
      {
        id: "3-1",
        url: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1600&q=80",
        alt: "Aspvägen Fågelsången",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.4385,
    longitude: 17.9525,
    bidStatus: "Budgivning",
    brokerId: "broker-1",
    createdAt: "2026-09-03T10:00:00Z",
    updatedAt: "2026-09-13T12:00:00Z",
    isFeatured: true,
  },
  {
    id: "4",
    slug: "timotejvagen-114-rotebro",
    title: "4 rok i Rotebro, Sollentuna",
    address: "Timotejvägen 114",
    city: "Sollentuna",
    area: "Rotebro",
    zipCode: "192 70",
    price: 4475000,
    pricePerSqm: 38248,
    status: "for_sale",
    type: "lagenhet",
    rooms: 4,
    livingArea: 117,
    description:
      "Rymlig 4 rok om 117 kvm i Rotebro, Sollentuna. Bra ytor och närhet till pendeltåg och service. Objekt via HusmanHagberg.",
    shortDescription: "4 rok, 117 kvm i Rotebro. 4 475 000 kr.",
    features: ["Nära pendeltåg", "Förråd", "Rymlig"],
    images: [
      {
        id: "4-1",
        url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1600&q=80",
        alt: "Timotejvägen Rotebro",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.4785,
    longitude: 17.9185,
    bidStatus: "Till salu",
    brokerId: "broker-1",
    createdAt: "2026-09-04T11:00:00Z",
    updatedAt: "2026-09-14T08:00:00Z",
    isFeatured: false,
  },
  {
    id: "5",
    slug: "molnstigen-37e-vasjon",
    title: "Modern 3:a i Väsjön, Sollentuna",
    address: "Molnstigen 37E",
    city: "Sollentuna",
    area: "Väsjön",
    zipCode: "192 79",
    price: 3395000,
    pricePerSqm: 53889,
    status: "for_sale",
    type: "lagenhet",
    rooms: 3,
    livingArea: 63,
    yearBuilt: 2023,
    floor: 1,
    monthlyFee: 1489,
    description:
      "Läckert designad etagelägenhet om 63 kvm högst upp med utsikt över Väsjön. Nästan nyskick (2023), egen laddplats möjlig. Objekt via HusmanHagberg Sollentuna.",
    shortDescription: "3 rok etage, 63 kvm i Väsjön. Accepterat pris 3 395 000 kr.",
    features: ["Nyproduktion", "Etagelägenhet", "Utsikt", "Laddplats möjlig"],
    images: [
      {
        id: "5-1",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80",
        alt: "Molnstigen Väsjön",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.4585,
    longitude: 17.9885,
    bidStatus: "Accepterat pris",
    brokerId: "broker-1",
    createdAt: "2026-09-05T09:00:00Z",
    updatedAt: "2026-09-14T07:00:00Z",
    isFeatured: true,
  },
  {
    id: "6",
    slug: "bygatan-76-tureberg",
    title: "3 rok på Bygatan i Tureberg",
    address: "Bygatan 76",
    city: "Sollentuna",
    area: "Tureberg",
    zipCode: "191 45",
    price: 2750000,
    pricePerSqm: 31609,
    status: "for_sale",
    type: "lagenhet",
    rooms: 3,
    livingArea: 87,
    description:
      "Trevlig 3 rok om 87 kvm i Tureberg, centralt i Sollentuna med närhet till centrum, pendeltåg och service. Objekt via HusmanHagberg.",
    shortDescription: "3 rok, 87 kvm i Tureberg. 2 750 000 kr.",
    features: ["Centralt", "Nära pendeltåg", "Förråd"],
    images: [
      {
        id: "6-1",
        url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1600&q=80",
        alt: "Bygatan Tureberg",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.4288,
    longitude: 17.9488,
    bidStatus: "Budgivning",
    brokerId: "broker-1",
    createdAt: "2026-09-06T10:00:00Z",
    updatedAt: "2026-09-13T15:00:00Z",
    isFeatured: false,
  },
  {
    id: "7",
    slug: "folkungavagen-21-haggvik",
    title: "3 rok på Folkungavägen i Häggvik",
    address: "Folkungavägen 21, 2 tr",
    city: "Sollentuna",
    area: "Häggvik",
    zipCode: "191 44",
    price: 2850000,
    pricePerSqm: 37353,
    status: "for_sale",
    type: "lagenhet",
    rooms: 3,
    livingArea: 76.3,
    floor: 2,
    description:
      "Välplanerad 3 rok om ca 76 kvm i Häggvik, Sollentuna. Bra läge med närhet till service och kommunikationer. Objekt via HusmanHagberg.",
    shortDescription: "3 rok, 76 kvm i Häggvik. 2 850 000 kr.",
    features: ["Häggvik", "Förråd", "Bra kommunikationer"],
    images: [
      {
        id: "7-1",
        url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1600&q=80",
        alt: "Folkungavägen Häggvik",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.4412,
    longitude: 17.9325,
    bidStatus: "Budgivning",
    brokerId: "broker-1",
    createdAt: "2026-09-07T11:00:00Z",
    updatedAt: "2026-09-12T14:00:00Z",
    isFeatured: false,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    firstName: "Erik",
    lastName: "Lindqvist",
    email: "erik.lindqvist@email.com",
    phone: "+46 70 123 45 67",
    preferredAreas: ["Edsviken", "Viby", "Tureberg"],
    budgetMin: 3000000,
    budgetMax: 12000000,
    propertyTypes: ["lagenhet", "villa"],
    familySituation: "Familj",
    buyProbability: 0.8,
    sellProbability: 0.15,
    notes: "Intresserad av Sollentuna, gärna Edsviken eller Viby.",
    source: "Webb",
    lastContactAt: "2026-09-13T14:20:00Z",
    createdAt: "2026-08-20T09:00:00Z",
    tags: ["hot-lead"],
  },
  {
    id: "c2",
    firstName: "Anna",
    lastName: "Bergström",
    email: "anna.bergstrom@email.com",
    phone: "+46 73 987 65 43",
    preferredAreas: ["Häggvik", "Rotebro", "Väsjön"],
    budgetMin: 2500000,
    budgetMax: 5000000,
    propertyTypes: ["lagenhet"],
    familySituation: "Par",
    buyProbability: 0.65,
    sellProbability: 0.4,
    notes: "Vill se 3–4 rok i Sollentuna.",
    source: "Referens",
    lastContactAt: "2026-09-12T11:00:00Z",
    createdAt: "2026-08-10T10:00:00Z",
    tags: ["buyer"],
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: "m1",
    title: "Visning – Manhemsvägen 16B",
    type: "viewing",
    propertyId: "1",
    startTime: "2026-09-15T14:00:00",
    endTime: "2026-09-15T15:00:00",
    location: "Manhemsvägen 16B, Edsviken",
    status: "scheduled",
  },
  {
    id: "m2",
    title: "Kundmöte – Erik Lindqvist",
    type: "consultation",
    customerId: "c1",
    startTime: "2026-09-15T10:00:00",
    endTime: "2026-09-15T11:00:00",
    location: "Kontor Sollentuna / videomöte",
    status: "scheduled",
  },
  {
    id: "m3",
    title: "Värdering – Sollentuna",
    type: "valuation",
    startTime: "2026-09-16T13:00:00",
    endTime: "2026-09-16T14:30:00",
    location: "Enligt överenskommelse",
    status: "scheduled",
  },
];

export const mockLeads: Lead[] = [
  {
    id: "l1",
    name: "Johan Svensson",
    email: "johan.s@email.com",
    phone: "+46 70 555 12 34",
    message: "Intresserad av villa/större lägenhet i Edsviken eller Viby.",
    source: "Webbformulär",
    interest: "buy",
    score: 85,
    status: "new",
    createdAt: "2026-09-14T08:30:00Z",
  },
  {
    id: "l2",
    name: "Maria Holm",
    email: "maria.holm@email.com",
    message: "Vill boka värdering av bostad i Tureberg.",
    source: "Chat",
    interest: "sell",
    score: 92,
    status: "new",
    createdAt: "2026-09-14T11:15:00Z",
  },
];

export const mockStats: DashboardStats = {
  todayMeetings: 3,
  newLeads: 7,
  activeDeals: 12,
  upcomingViewings: 5,
  monthlyRevenue: 1850000,
  conversionRate: 24.5,
  totalListings: 7,
  soldThisMonth: 4,
};

export const mockRecommendations: AIRecommendation[] = [
  {
    id: "r1",
    type: "call",
    title: "Ring Maria Holm idag",
    description: "Vill ha värdering i Tureberg. Hög säljsannolikhet.",
    priority: "high",
    createdAt: "2026-09-14T07:00:00Z",
  },
  {
    id: "r2",
    type: "followup",
    title: "Följ upp – Manhemsvägen 16B",
    description: "Premiumobjekt i Edsviken. Kontakta leads som söker större bostad.",
    priority: "high",
    relatedPropertyId: "1",
    createdAt: "2026-09-14T07:05:00Z",
  },
  {
    id: "r3",
    type: "call",
    title: "Boka möte med Johan Svensson",
    description: "Intresserad av Edsviken/Viby. Militärvägen och Manhemsvägen kan passa.",
    priority: "high",
    createdAt: "2026-09-14T07:10:00Z",
  },
  {
    id: "r4",
    type: "marketing",
    title: "Lyft Väsjön-objektet",
    description: "Molnstigen 37E (nyproduktion) passar köpare som vill ha modern standard.",
    priority: "medium",
    relatedPropertyId: "5",
    createdAt: "2026-09-14T07:15:00Z",
  },
];
