import { Property, Customer, Meeting, Lead, DashboardStats, AIRecommendation } from "@/types";

export const mockProperties: Property[] = [
  {
    id: "1",
    slug: "elegans-ostermalm-4rok",
    title: "Exklusiv våning med takterrass på Östermalm",
    address: "Strandvägen 7",
    city: "Stockholm",
    area: "Östermalm",
    zipCode: "114 56",
    price: 28500000,
    pricePerSqm: 142500,
    status: "for_sale",
    type: "lagenhet",
    rooms: 4,
    livingArea: 200,
    yearBuilt: 1912,
    floor: 5,
    totalFloors: 6,
    monthlyFee: 8500,
    operatingCost: 3200,
    energyClass: "C",
    description:
      "En sällsynt möjlighet att förvärva en av Östermalms mest eftertraktade våningar. Denna spektakulära residens erbjuder generösa sällskapsytor, tre sovrum, två badrum samt en privat takterrass med panoramautsikt över Djurgården och Stockholms inlopp. Renoverad med största omsorg och respekt för det ursprungliga sekelskifteshantverket.",
    shortDescription:
      "Spektakulär 4:a med takterrass och utsikt över vattnet. Sekelskifte möter modern lyx.",
    features: [
      "Takterrass",
      "Öppen spis",
      "Hiss",
      "Balkong",
      "Parkering",
      "Förråd",
      "Golvvärme",
      "Säkerhetsdörr",
    ],
    images: [
      {
        id: "1-1",
        url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80",
        alt: "Vardagsrum med högt i tak",
        isPrimary: true,
        order: 1,
      },
      {
        id: "1-2",
        url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80",
        alt: "Kök i marmor",
        order: 2,
      },
      {
        id: "1-3",
        url: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1600&q=80",
        alt: "Master bedroom",
        order: 3,
      },
    ],
    latitude: 59.3315,
    longitude: 18.0872,
    viewingDates: ["2026-09-14T14:00:00", "2026-09-17T18:00:00"],
    bidStatus: "Budgivning pågår",
    brokerId: "broker-1",
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-09-10T14:30:00Z",
    isFeatured: true,
  },
  {
    id: "2",
    slug: "modern-villa-djursholm",
    title: "Arkitektritad villa i Djursholm",
    address: "Vasavägen 42",
    city: "Danderyd",
    area: "Djursholm",
    zipCode: "182 63",
    price: 42000000,
    pricePerSqm: 105000,
    status: "for_sale",
    type: "villa",
    rooms: 8,
    livingArea: 400,
    plotArea: 1850,
    yearBuilt: 2019,
    monthlyFee: 0,
    operatingCost: 6800,
    energyClass: "A",
    description:
      "En mästerligt utformad villa signerad en av Sveriges ledande arkitekter. Här möts skandinavisk minimalism med lyxig materialitet. Generösa glaspartier, inomhuspool, spa och en park liknande tomt med fullständig avskildhet.",
    shortDescription:
      "Arkitektvilla med pool, spa och park-tomt i hjärtat av Djursholm.",
    features: [
      "Pool",
      "Spa",
      "Garage för 3 bilar",
      "Hemmabio",
      "Vinrum",
      "Smart home",
      "Bergvärme",
      "Säkerhetssystem",
    ],
    images: [
      {
        id: "2-1",
        url: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=1600&q=80",
        alt: "Villa exteriör",
        isPrimary: true,
        order: 1,
      },
      {
        id: "2-2",
        url: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=1600&q=80",
        alt: "Vardagsrum",
        order: 2,
      },
    ],
    latitude: 59.3985,
    longitude: 18.0572,
    viewingDates: ["2026-09-15T13:00:00"],
    brokerId: "broker-1",
    createdAt: "2026-08-25T09:00:00Z",
    updatedAt: "2026-09-11T11:00:00Z",
    isFeatured: true,
  },
  {
    id: "3",
    slug: "penthouse-sodermalm",
    title: "Penthouse med takterrass på Södermalm",
    address: "Hornsgatan 88",
    city: "Stockholm",
    area: "Södermalm",
    zipCode: "118 21",
    price: 18900000,
    pricePerSqm: 157500,
    status: "for_sale",
    type: "lagenhet",
    rooms: 3,
    livingArea: 120,
    yearBuilt: 2018,
    floor: 7,
    totalFloors: 7,
    monthlyFee: 6200,
    operatingCost: 2100,
    energyClass: "B",
    description:
      "Ljus och luftig penthouse i nyproduktion med generös takterrass och storslagen utsikt över Riddarfjärden. Öppen planlösning, golv-till-tak-fönster och material i absolut högsta klass.",
    shortDescription:
      "Nyproducerad penthouse med takterrass och vy över Riddarfjärden.",
    features: ["Takterrass", "Hiss", "Förråd", "Parkeringsplats", "Balkong"],
    images: [
      {
        id: "3-1",
        url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1600&q=80",
        alt: "Penthouse vardagsrum",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.3175,
    longitude: 18.0482,
    viewingDates: ["2026-09-16T17:00:00", "2026-09-20T12:00:00"],
    brokerId: "broker-1",
    createdAt: "2026-09-01T10:00:00Z",
    updatedAt: "2026-09-12T09:00:00Z",
    isFeatured: false,
  },
  {
    id: "4",
    slug: "klassisk-våning-vasastan",
    title: "Klassisk våning i Vasastan",
    address: "Odengatan 65",
    city: "Stockholm",
    area: "Vasastan",
    zipCode: "113 22",
    price: 12400000,
    pricePerSqm: 112727,
    finalPrice: 13150000,
    status: "sold",
    type: "lagenhet",
    rooms: 3.5,
    livingArea: 110,
    yearBuilt: 1928,
    floor: 3,
    totalFloors: 5,
    monthlyFee: 4800,
    energyClass: "D",
    description:
      "Charmig och välplanerad våning i ett av Vasastans mest omtyckta kvarter. Originaldetaljer i kombination med modern komfort.",
    shortDescription: "Såld – Charmig 3,5:a med originaldetaljer i Vasastan.",
    features: ["Balkong", "Hiss", "Förråd", "Kakelugn"],
    images: [
      {
        id: "4-1",
        url: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=80",
        alt: "Vardagsrum med kakelugn",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.3445,
    longitude: 18.0452,
    brokerId: "broker-1",
    createdAt: "2026-07-10T10:00:00Z",
    updatedAt: "2026-08-28T16:00:00Z",
  },
  {
    id: "5",
    slug: "lyxig-radhus-nacka",
    title: "Lyxigt radhus med sjöutsikt i Nacka",
    address: "Saltsjöbaden 12",
    city: "Nacka",
    area: "Saltsjöbaden",
    zipCode: "133 35",
    price: 16500000,
    pricePerSqm: 94300,
    status: "for_sale",
    type: "radhus",
    rooms: 6,
    livingArea: 175,
    plotArea: 280,
    yearBuilt: 2015,
    operatingCost: 4100,
    energyClass: "B",
    description:
      "Exklusivt radhus i första parkett mot vattnet. Generösa ytor i tre plan, privat brygga och en oslagbar boendemiljö.",
    shortDescription: "Radhus i första parkett med privat brygga och sjöutsikt.",
    features: ["Sjöutsikt", "Privat brygga", "Garage", "Balkong", "Trädgård"],
    images: [
      {
        id: "5-1",
        url: "https://images.unsplash.com/photo-1600047509807-ba8f04d8c6a6?w=1600&q=80",
        alt: "Radhus mot vattnet",
        isPrimary: true,
        order: 1,
      },
    ],
    latitude: 59.2885,
    longitude: 18.3012,
    viewingDates: ["2026-09-18T15:00:00"],
    brokerId: "broker-1",
    createdAt: "2026-09-05T08:00:00Z",
    updatedAt: "2026-09-12T10:00:00Z",
    isFeatured: true,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "c1",
    firstName: "Erik",
    lastName: "Lindqvist",
    email: "erik.lindqvist@email.com",
    phone: "+46 70 123 45 67",
    preferredAreas: ["Östermalm", "Vasastan", "Djurgården"],
    budgetMin: 15000000,
    budgetMax: 30000000,
    propertyTypes: ["lagenhet"],
    familySituation: "Par utan barn",
    buyProbability: 0.82,
    sellProbability: 0.15,
    notes: "Intresserad av objekt med takterrass. Vill gärna se Strandvägen.",
    source: "Hemnet",
    lastContactAt: "2026-09-11T14:20:00Z",
    createdAt: "2026-08-15T09:00:00Z",
    tags: ["hot-lead", "premium"],
  },
  {
    id: "c2",
    firstName: "Anna",
    lastName: "Bergström",
    email: "anna.bergstrom@email.com",
    phone: "+46 73 987 65 43",
    preferredAreas: ["Djursholm", "Lidingö"],
    budgetMin: 25000000,
    budgetMax: 50000000,
    propertyTypes: ["villa"],
    familySituation: "Familj med två barn",
    buyProbability: 0.65,
    sellProbability: 0.78,
    notes: "Säljer nuvarande villa i Stocksund. Vill uppgradera.",
    source: "Referens",
    lastContactAt: "2026-09-10T11:00:00Z",
    createdAt: "2026-07-20T10:00:00Z",
    tags: ["seller", "buyer"],
  },
];

export const mockMeetings: Meeting[] = [
  {
    id: "m1",
    title: "Värdering – Vasavägen 42",
    type: "valuation",
    customerId: "c2",
    propertyId: "2",
    startTime: "2026-09-13T10:00:00",
    endTime: "2026-09-13T11:30:00",
    location: "Vasavägen 42, Djursholm",
    status: "scheduled",
  },
  {
    id: "m2",
    title: "Visning – Strandvägen 7",
    type: "viewing",
    propertyId: "1",
    startTime: "2026-09-14T14:00:00",
    endTime: "2026-09-14T15:00:00",
    location: "Strandvägen 7",
    status: "scheduled",
  },
  {
    id: "m3",
    title: "Konsultation – Erik Lindqvist",
    type: "consultation",
    customerId: "c1",
    startTime: "2026-09-13T15:00:00",
    endTime: "2026-09-13T16:00:00",
    location: "Kontoret / Videomöte",
    status: "scheduled",
  },
];

export const mockLeads: Lead[] = [
  {
    id: "l1",
    name: "Johan Svensson",
    email: "johan.s@email.com",
    phone: "+46 70 555 12 34",
    message: "Intresserad av villor i Djursholm-området runt 30-40 MSEK.",
    source: "Webbformulär",
    interest: "buy",
    score: 78,
    status: "new",
    createdAt: "2026-09-12T08:30:00Z",
  },
  {
    id: "l2",
    name: "Maria Holm",
    email: "maria.holm@email.com",
    message: "Vill sälja min lägenhet på Östermalm. Behöver värdering.",
    source: "Chat",
    interest: "sell",
    score: 91,
    status: "new",
    createdAt: "2026-09-12T14:15:00Z",
  },
];

export const mockStats: DashboardStats = {
  todayMeetings: 3,
  newLeads: 7,
  activeDeals: 12,
  upcomingViewings: 5,
  monthlyRevenue: 1850000,
  conversionRate: 24.5,
  totalListings: 18,
  soldThisMonth: 4,
};

export const mockRecommendations: AIRecommendation[] = [
  {
    id: "r1",
    type: "call",
    title: "Ring Maria Holm idag",
    description:
      "Hög säljsannolikhet (91). Hon hörde av sig via chatten om värdering på Östermalm. Bästa tid: 10:00–12:00.",
    priority: "high",
    createdAt: "2026-09-12T07:00:00Z",
  },
  {
    id: "r2",
    type: "price",
    title: "Överväg prisjustering – Hornsgatan 88",
    description:
      "Objektet har legat ute 11 dagar med lägre engagemang än jämförbara. Marknadsdata tyder på att -3% kan öka visningsfrekvensen markant.",
    priority: "medium",
    relatedPropertyId: "3",
    createdAt: "2026-09-12T07:05:00Z",
  },
  {
    id: "r3",
    type: "followup",
    title: "Följ upp Erik Lindqvist",
    description:
      "Han var mycket intresserad av Strandvägen 7. Skicka personlig uppdatering om budgivningen.",
    priority: "high",
    relatedCustomerId: "c1",
    relatedPropertyId: "1",
    createdAt: "2026-09-12T07:10:00Z",
  },
  {
    id: "r4",
    type: "marketing",
    title: "Öka exponering – Vasavägen 42",
    description:
      "Premiumobjekt med hög potential. Rekommenderar riktad kampanj mot målgrupp i Stocksund/Djursholm + Instagram Stories.",
    priority: "medium",
    relatedPropertyId: "2",
    createdAt: "2026-09-12T07:15:00Z",
  },
];
